site_name: Lassie - Earthquake Detector
site_description: The friendly earthquake detector
repo_url: https://github.com/pyrocko/lassie-v2
repo_name: pyrocko/lassie-v2
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/theme
  palette:
  - scheme: default
    primary: blue grey
    toggle:
       icon: material/toggle-switch
       name: Switch to dark mode
    # Palette toggle for dark mode
  - scheme: slate
    primary: blue grey
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/logo.webp
  features:
    - navigation.tabs
    - search.suggest
    - announce.dismiss
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - attr_list

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - lassie

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - 🐕‍🦺 Earthquake Detector:
    - Welcome: index.md
    - Getting Started: getting_started.md
    - Visualising Detections: visualizing_results.md
  - Components:
    - Seismic Data: components/seismic_data.md
    - Ray Tracer: components/ray_tracer.md
    - Image Function: components/image_function.md
    - Octree: components/octree.md
