
[build-system]
requires = [
    "wheel",
    "setuptools >= 61.0.0",
    "oldest-supported-numpy",
    "setuptools_scm[toml]>=6.2",
]
build-backend = "setuptools.build_meta"

[project]
name = "lassie"
requires-python = ">=3.10"
license = { text = "GPLv3" }
dynamic = ["version"]

description = "Lassie - The friendly earthquake detector."
readme = "README.md"
authors = [
    { name = "Marius Paul Isken", email = "mi@gfz-potsdam.de" },
    { name = "Sebastian Heimann", email = "heimann@uni-potsdam.de" },
    { name = "Marius Kriegerowski", email = "mk@quakesaver.de" },
]
maintainers = [
    { name = "Marius Paul Isken", email = "mi@gfz-potsdam.de" },
    { name = "Sebastian Heimann", email = "heimann@uni-potsdam.de" },
]
keywords = ["earthquake", "detection", "locatiosation", "stacking-migration"]

dependencies = [
    "numpy>=1.17.3",
    "scipy>=1.8.0",
    "pyrocko>=2022.06.10",
    "seisbench>=0.5.0",
    "pydantic>=2.4.2",
    "aiohttp>=3.8",
    "aiohttp_cors>=0.7.0",
    "typing-extensions>=4.6",
    "lru-dict>=1.2",
    "rich>=13.4",
    "nest_asyncio>=1.5",
    "pyevtk>=1.6",
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Operating System :: POSIX",
    "Operating System :: MacOS",
    "Typing :: Typed",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=3.4",
    "black>=23.7",
    "ruff>=0.1",
    "pytest>=7.4",
    "pytest-asyncio>=0.21",
    "mkdocs-material>=9.4",
    "mkdocstrings[python]>=0.23",
]

[project.scripts]
lassie = "lassie.apps.lassie:main"

[tool.setuptools.packages.find]
include = ["lassie*"]

[project.urls]
Home = "https://pyrocko.org"
GitHub = "https://git.pyrocko.org/pyrocko/lassie"
Issues = "https://git.pyrocko.org/pyrocko/lassie/issues"

[tool.setuptools.package-data]
"lassie.data" = ["*.wav"]

[tool.setuptools_scm]

[tool.ruff]
extend-select = [
    'W',
    'N',
    'DTZ',
    'FA',
    'G',
    'RET',
    'SIM',
    'B',
    'RET',
    'C4',
    'I',
    'RUF',
]
target-version = 'py310'
ignore = ["RUF012", "RUF009"]

[tool.pytest.ini_options]
markers = ["plot: plot figures in tests"]
