name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  pypi-publish:
    name: Upload release to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs: [build_wheels, make_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/qseek
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: Download all the wheels and sdists
      uses: actions/download-artifact@v3
      with:
        pattern: cibw-*
        path: dist/
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
